### ISSUE TITLE
Final Thoughts

### ISSUE THREAD

**Issue by MBenkhayal** [kdunn13/Assignment1#3]
Hey Kevin, everything looks great! Your code is clean and well documented, the graphs look awesome, and overall I really like the work you've done!

**Comment by MBenkhayal** [comment]
One thing I noticed, you left some parts of the assignment statement in your solution. I don't really think these are necessary, and you probably could delete them.

**Comment by kdunn13** [comment]
Thank you, I've just finished the extra credit.
